excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods

line_length:
  - 150 # warning
  - 200 # error

cyclomatic_complexity:
  ignores_case_statements: true